"""empty message

Revision ID: fde4d26228b0
Revises: 11822d95327f
Create Date: 2020-10-12 10:32:54.293401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fde4d26228b0'
down_revision = '11822d95327f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_token', table_name='user')
    op.drop_column('user', 'token')
    op.drop_column('user', 'token_expiration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_expiration', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('token', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=True))
    op.create_index('ix_user_token', 'user', ['token'], unique=True)
    # ### end Alembic commands ###
